In [13]:
import numpy as jtn

In [41]:
j1=jtn.arange(3,10,2)
print(j1)
j1[1]
j1[3]
j1[-1]

[3 5 7 9]

np.int64(9)

In [40]:
j1=jtn.random.rand(2,3)*100
j1

array([[23.35600732, 25.01825718, 34.94847498],
       [ 8.73624088, 47.43202487, 61.15808178]])

In [39]:
j1=(jtn.random.rand(3,3)*100).astype(int)
j1

array([[99, 80, 46],
       [23, 48, 13],
       [73, 92, 48]])

In [50]:
j1=(jtn.random.rand(4,4)*100).astype(int)
j1
print(j1)
j1[:,0]     # jtn(row,col)
j1[2,:]
j1[0,:]
j1[:,3]
j1[:,3:1]
j1[:]

[[53 85 33 80]
 [43 30 92 84]
 [86 25  9 85]
 [61 46 87 74]]

array([[53, 85, 33, 80],
       [43, 30, 92, 84],
       [86, 25,  9, 85],
       [61, 46, 87, 74]])

In [ ]:
j1=(jtn.random.rand(5,5)*100).astype(int)
print(j1)
j1[:]                   #all
j1[0]                   # first row
j1[-1]                  # last row
j1[:3]                  # first 3 row
j1[-3:]                 # last 3 row
j1[2:6]                 # element from  2 to 5
j1[3:]                 # element from  3 to end
j1[:5]                 # element f rom  start to index 4

[[39 19 37 81 53]
 [42 77 94 41 93]
 [65 31 50 60 12]
 [44 10 99 90  6]
 [95 48 37 98 71]]

array([[39, 19, 37, 81, 53],
       [42, 77, 94, 41, 93],
       [65, 31, 50, 60, 12],
       [44, 10, 99, 90,  6],
       [95, 48, 37, 98, 71]])

In [81]:
# 2d array
j1=(jtn.random.rand(3,3)*100).astype(int)
print(j1)
j1[0]
j1[1]
j1[2]
j1[-1]
j1[0:2]
j1[1:]
j1[0:3]
j1[1,:]
j1[2,:]
j1[:,:]

[[56 97 14]
 [39 53 21]
 [86 56 15]]

array([[56, 97, 14],
       [39, 53, 21],
       [86, 56, 15]])

In [86]:
j1=(jtn.random.rand(3,3)*100).astype(int)
print(j1)
j1[1,1:2]
j1[2,1:2]
j1[1,0:1]

[[ 0 73 16]
 [20 30 90]
 [38  1 29]]

array([20])

In [93]:
j1=(jtn.random.rand(3,3)*100).astype(int)
print(j1)
j1[0:2,0:2]
j1[1:3,1:3]
j1[0:,0:2]

[[57 63 37]
 [65 42 65]
 [56 60 70]]

array([[57, 63],
       [65, 42],
       [56, 60]])

In [100]:
j1=(jtn.random.rand(4,4)*100).astype(int)
print(j1)
j1[2:4,0:2]
j1[1:,2:4]

[[94 71 60  9]
 [55 42 36 70]
 [95 26 46 34]
 [63  0 85 21]]

array([[36, 70],
       [46, 34],
       [85, 21]])

In [101]:
# 3d array

In [114]:
j1=(jtn.random.rand(3,3,3)*100).astype(int)
print(j1)
j1[2,1,1]

[[[41 75 23]
  [34 82 50]
  [ 9 89 75]]

 [[11 49 17]
  [34  7 36]
  [88 10  4]]

 [[98 84 34]
  [36 68 62]
  [10 21 67]]]

np.int64(68)

In [115]:
# Aggregation Function

In [140]:
import math
j1=jtn.array([10,20,13,12,19])
print(j1)
sum(j1)
min(j1)
max(j1)
jtn.var(j1)
jtn.mean(j1)
jtn.median(j1)

[10 20 13 12 19]

np.float64(13.0)

## Pandas

In [ ]:
pip install pandas

In [7]:
import pandas as putin
import numpy as nutin

In [8]:
p1=putin.Series([10,20,30,40,50])
p1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [9]:
n1=nutin.array([10,20,30,40,50])
p1=putin.Series(n1)
p1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [12]:
d1={
    "name": "jakala",
    "course": "BCA",
    "Rollno": 1234,
    "address": "jaouse"
}

p1=putin.Series(d1)
p1

name       jakala
course        BCA
Rollno       1234
address    jaouse
dtype: object

In [ ]:
import numpy as np
import pandas as pd


#Series

n1=np.array([10,20,30,40,50])
p1=pd.Series(n1,index=["a","b", "c", "d","e"])
print(n1)
print(p1)
p1["c"]
p1[["a","c", "e"]]

[10 20 30 40 50]
a    10
b    20
c    30
d    40
e    50
dtype: int64

a    10
c    30
e    50
dtype: int64

In [21]:
s1=pd.Series(np.arange(2,9,2))
s1

0    2
1    4
2    6
3    8
dtype: int64

In [24]:
s1=pd.Series(np.arange(2,9))
print(s1)
s1[1:5]

0    2
1    3
2    4
3    5
4    6
5    7
6    8
dtype: int64

1    3
2    4
3    5
4    6
dtype: int64

In [36]:
s1=pd.Series([10,20,30,40,50],index=["a","b","c",'d',"e"], name="ankit")
print(s1)
s1.index
s1.values
s1.dtype
s1.shape
s1.size
s1.ndim
s1.name

a    10
b    20
c    30
d    40
e    50
Name: ankit, dtype: int64

'ankit'

In [59]:
s1=pd.Series([10,20,30,40,50],index=["a","b","c",'d',"e"], name="ankit")
print(s1)
sum(s1)
np.mean(s1)
np.median(s1)
# mode(s1)
# min(s1)
# max(s1)
# count(s1)

a    10
b    20
c    30
d    40
e    50
Name: ankit, dtype: int64

np.float64(30.0)

In [61]:
import pandas as pd
import numpy as np

s1 = pd.Series([10, 20, 30, 40, 50], index=["a", "b", "c", 'd', "e"], name="ankit")

print(s1.mode()) 

print(s1.count())

0    10
1    20
2    30
3    40
4    50
Name: ankit, dtype: int64
5

In [70]:
import numpy as np
import pandas as pd

# Dataframe
d1={
    "name": ["putin", "jutin"],
      "city":["kota","delhi"],
    "age":[34,23]
}
all=pd.DataFrame(d1)
all

    name   city  age
0  putin   kota   34
1  jutin  delhi   23

In [1]:
import numpy as np
import pandas as pd

# Dataframe
d1={
    "name": ["putin", "jutin"],
      "city":["kota","delhi"],
    "age":[34,23]
}
all=pd.DataFrame(d1,columns=["n", 'c',"c"])
all

Empty DataFrame
Columns: [n, c, c]
Index: []

In [3]:
file=pd.read_csv("Pokemon.csv")
file

,number,name,type1,type2,total,hp,attack,defense,sp_attack,sp_defense,speed,generation,legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,3,Gigantamax Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1067,896,Glastrier,Ice,NaN,580,100,145,130,65,110,30,8,True
1068,897,Spectrier,Ghost,NaN,580,100,65,60,145,80,130,8,True
1069,898,Calyrex,Psychic,Grass,500,100,80,80,80,80,80,8,True
1070,898,Ice Rider Calyrex,Psychic,Ice,680,100,165,150,85,130,50,8,True
1071,898,Shadow Rider Calyrex,Psychic,Ghost,680,100,85,80,165,100,150,8,True

In [5]:
pk=pd.DataFrame(file)
p1=pd.Series(pk["name"])
p1

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3              Mega Venusaur
4        Gigantamax Venusaur
                ...
1067               Glastrier
1068               Spectrier
1069                 Calyrex
1070       Ice Rider Calyrex
1071    Shadow Rider Calyrex
Name: name, Length: 1072, dtype: str

In [ ]:
file=pd.read_json("train.json")
file

,train_no,train_name,route,route_code,KMT,WL,BPQ,NGP,BCT,ST,KOTA,JP,NDLS
0,13240,Kota-Patna Express,"[Kota, Indargarh Sumerganj Mandi, Sawai Madhop...","{'KOTA': 'Kota', 'IDG': 'Indargarh Sumerganj M...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,13238,Kota-Patna Express,"[Kota, Indargarh Sumerganj Mandi, Sawai Madhop...","{'KOTA': 'Kota', 'IDG': 'Indargarh Sumerganj M...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,13237,Patna-Kota Express,"[Patna, Danapur, Bihta, Ara, Dumroan, Buxar, Z...","{'PNBE': 'Patna', 'DNR': 'Danapur', 'BTA': 'Bi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,13239,Patna-Kota Express,"[Patna, Danapur, Bihta, Ara, Buxar, Zamania, P...","{'PNBE': 'Patna', 'DNR': 'Danapur', 'BTA': 'Bi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,12239,Hisar Duronto Express,"[Ratlam, Kota, Sawai Madhopur, Jaipur]","{'RTM': 'Ratlam', 'KOTA': 'Kota', 'SWM': 'Sawa...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,12465,Ranthambhore SF Express,"[Dakaniya Talav, Kota, Kapren, Lakheri, Indarg...","{'DKAE': 'Dakaniya Talav', 'KOTA': 'Kota', 'KP...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,22933,Jaipur SF Express,"[Bandra Terminus, Borivali, Vapi, Surat, Bharu...","{'BDTS': 'Bandra Terminus', 'BVI': 'Borivali',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,22935,Jaipur SF Express,"[Jaipur, Durgapura, Sawai Madhopur, Kota, Ramg...","{'SWM': 'Sawai Madhopur', 'KOTA': 'Kota', 'RMA...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,12955,Mumbai Central Jaipur SF Express,"[Mumbai Central, Borivali, Vapi, Surat, Ankles...","{'BCT': 'Mumbai Central', 'BVI': 'Borivali', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,67890,Kolkata-Delhi Superfast,"[Kolkata, Patna, Varanasi, Kanpur Central, Luc...","{'Kolkata': 'Kolkata', 'PNBE': 'Patna', 'BSB':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,12904,Golden Temple Mail,"[Hazrat Nizamuddin, Faridabad, Mathura, Bharat...","{'NZM': 'Hazrat Nizamuddin', 'FDB': 'Faridabad...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12622,Tamil Nadu Express,"[New Delhi, Agra Cantt, Gwalior, VGL Jhansi, B...","{'NDLS': 'New Delhi', 'AGC': 'Agra Cantt', 'GW...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,10622,Delhi Chennai Rajdhani Express,"[New Delhi, Jaipur, Kota, Surat, Mumbai , Nagp...","{'NDLS': 'New Delhi', 'JP': 'Jaipur', 'KOTA': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,12424,Dibrugarh Rajdhani Express,"[New Delhi, Jaunpur Central, Prayagraj, Pt.DD ...","{'NDLS': 'New Delhi', 'JNU': 'Jaunpur Junction...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,20506,Dibrugarh Rajdhani Express,"[New Delhi, Moradabad, Bareilly, Lucknow, Vara...","{'NDLS': 'New Delhi', 'MB': 'Moradabad', 'BE':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,20503,New Delhi Rajdhani Express,"[Dibrugarh, North Lakhimpur, Harmuti, Rangapar...","{'DBRG': 'Dibrugarh', 'NLP': 'North Lakhimpur'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,10324,Dibrugarh Rajdhani Express,"[Dibrugarh, Dimapur, Rangia, Guwahati, Patna, ...","{'DBRG': 'Dibrugarh', 'DMV': 'Dimapur', 'RNY':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,10623,Delhi Rajdhani Express,"[Chennai, Vijayawada, Khammam, Warangal, Balha...","{'MAS': 'Chennai Central', 'BZA': 'Vijayawada'...",Khammam,Warangal,Balharshah,Nagpur,Mumbai Central,Surat,Kota,Jaipur,New Delhi
18,15667,Kamakhya Express,"[Kota, Sawai Madhopur, Bayana, Agra Fort, Tund...","{'KOTA': 'Kota', 'SWM': 'Sawai Madhopur', 'BXN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,15635,Guwahati Dwarka Express,"[Okha, Dwarka, Khambhalia, Jamnagar, Hapa, Raj...","{'OKHA': 'Okha', 'DWK': 'Dwarka', 'KMBL': 'Kha...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,22436,Varanasi Vande Bharat Express,"[New Delhi, Kanpur Central, Prayagraj , Varana...","{'NDLS': 'New Delhi', 'CNB': 'Kanpur Central',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22437,Varanasi Vande Bharat Express,"[Varanasi, Prayagraj , Kanpur Central, New Delhi]","{'BSB': 'Varanasi', 'PRYJ': 'Prayagraj', 'CNB'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,22438,Patna Vande Bharat Express,"[New Delhi, Patna]","{'NDLS': 'New Delhi', 'PNBE': 'Patna'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,22439,Patna Vande Bharat Express,"[Patna, New Delhi]","{'PNBE': 'Patna', 'NDLS': 'New Delhi'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
pk=pd.DataFrame(file)
p1=pd.Series(pk["route_code"])
p1

0     {'KOTA': 'Kota', 'IDG': 'Indargarh Sumerganj M...
1     {'KOTA': 'Kota', 'IDG': 'Indargarh Sumerganj M...
2     {'PNBE': 'Patna', 'DNR': 'Danapur', 'BTA': 'Bi...
3     {'PNBE': 'Patna', 'DNR': 'Danapur', 'BTA': 'Bi...
4     {'RTM': 'Ratlam', 'KOTA': 'Kota', 'SWM': 'Sawa...
5     {'DKAE': 'Dakaniya Talav', 'KOTA': 'Kota', 'KP...
6     {'BDTS': 'Bandra Terminus', 'BVI': 'Borivali',...
7     {'SWM': 'Sawai Madhopur', 'KOTA': 'Kota', 'RMA...
8     {'BCT': 'Mumbai Central', 'BVI': 'Borivali', '...
9     {'Kolkata': 'Kolkata', 'PNBE': 'Patna', 'BSB':...
10    {'NZM': 'Hazrat Nizamuddin', 'FDB': 'Faridabad...
11    {'NDLS': 'New Delhi', 'AGC': 'Agra Cantt', 'GW...
12    {'NDLS': 'New Delhi', 'JP': 'Jaipur', 'KOTA': ...
13    {'NDLS': 'New Delhi', 'JNU': 'Jaunpur Junction...
14    {'NDLS': 'New Delhi', 'MB': 'Moradabad', 'BE':...
15    {'DBRG': 'Dibrugarh', 'NLP': 'North Lakhimpur'...
16    {'DBRG': 'Dibrugarh', 'DMV': 'Dimapur', 'RNY':...
17    {'MAS': 'Chennai Central', 'BZA': 'Vijayawada'...
18    {'KOTA': 'Kota', 'SWM': 'Sawai Madhopur', 'BXN...
19    {'OKHA': 'Okha', 'DWK': 'Dwarka', 'KMBL': 'Kha...
20    {'NDLS': 'New Delhi', 'CNB': 'Kanpur Central',...
21    {'BSB': 'Varanasi', 'PRYJ': 'Prayagraj', 'CNB'...
22               {'NDLS': 'New Delhi', 'PNBE': 'Patna'}
23               {'PNBE': 'Patna', 'NDLS': 'New Delhi'}
Name: route_code, dtype: object